// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjX1Ip_3NdHnQReKGfpQcM6QqCTljH07s',
    appId: '1:452668032443:web:e153475d9acd3592bef09e',
    messagingSenderId: '452668032443',
    projectId: 'wmk-ngo-ding',
    authDomain: 'wmk-ngo-ding.firebaseapp.com',
    databaseURL: 'https://wmk-ngo-ding-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wmk-ngo-ding.appspot.com',
    measurementId: 'G-44LSKE00SV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-qw8jz918bw-MamXAJAjbOR6CwBLmN-I',
    appId: '1:452668032443:android:ef71441abfa1829abef09e',
    messagingSenderId: '452668032443',
    projectId: 'wmk-ngo-ding',
    databaseURL: 'https://wmk-ngo-ding-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wmk-ngo-ding.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQkhCwBZ1BegWrgdtwfXZKr3qVP3s2q4U',
    appId: '1:452668032443:ios:dc8deb284f71f3bfbef09e',
    messagingSenderId: '452668032443',
    projectId: 'wmk-ngo-ding',
    databaseURL: 'https://wmk-ngo-ding-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wmk-ngo-ding.appspot.com',
    iosBundleId: 'com.example.wmk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQkhCwBZ1BegWrgdtwfXZKr3qVP3s2q4U',
    appId: '1:452668032443:ios:883bb3eb229e8714bef09e',
    messagingSenderId: '452668032443',
    projectId: 'wmk-ngo-ding',
    databaseURL: 'https://wmk-ngo-ding-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wmk-ngo-ding.appspot.com',
    iosBundleId: 'com.example.wmk.RunnerTests',
  );
}
