<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class AnggotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('anggota')->insert([
            'nik' => '123',
            'no_anggota' => '1',
            'nama_lengkap' => 'John Doe',
            'masa_berlaku_ktp' => '2025-12-31',
            'tempat_lahir' => 'Jakarta',
            'tanggal_lahir' => '1990-01-01',
            'jenis_kelamin' => 'Laki-Laki',
            'alamat_ktp' => 'Jl. KTP No. 123',
            'kelurahan_ktp' => 'Kelurahan KTP',
            'kecamatan_ktp' => 'Kecamatan KTP',
            'kota_ktp' => 'Kota KTP',
            'kodepos_ktp' => '12345',
            'alamat' => 'Jl. Alamat No. 456',
            'kelurahan' => 'Kelurahan Alamat',
            'kecamatan' => 'Kecamatan Alamat',
            'kota' => 'Kota Alamat',
            'kodepos' => '54321',
            'no_telepon_rumah' => '021-12345678',
            'no_telepon_hp' => '081234567890',
            'status_tempat_tinggal' => 'Milik Sendiri',
            'menempati_alamat_tsb_sejak' => '2010-01-01',
            'pendidikan_terakhir' => 'SMA',
            'status_perkawinan' => 'Lajang',
            'nama_istri_suami' => 'Jane Doe',
            'jumlah_anak' => '2',
            'nama_ibu_kandung_pemohon' => 'Mother Doe',
            'npwp_pribadi' => '1234567890',
            'nama_ahli_waris' => 'Heir Doe',
            'hubungan_ahli_waris' => 'Anak',
            'no_telp_ext_kantor' => '123',
            'nip' => '123456789',
            'nomor_rekening' => '1234567890',
            'bagian' => 'IT',
            'tgl_masuk_keperusahaan' => '2010-01-01',
            'status_karyawan' => 'Karyawan Tetap',
            'foto' => 'john_doe.jpg',
            'foto_ktp' => 'ktp.jpg',
            'ttd' => 'john_doe_signature.jpg',
            'id_card' => 'id_card.jpg',
            'tanggal_daftar' => '2023-06-11',
            'tanggal_gabung' => '2023-06-11',
            'tanggal_berhenti' => null,
            'tanggal_req_berhenti' => null,
            'sebab_berhenti' => null,
            'password' => bcrypt('123'),
            'email' => 'john@gmail.com',
            'role' => 'ketua',
            'status' => 'Aktif',
        ]);

        DB::table('anggota')->insert([
            'nik' => '812',
            'no_anggota' => '4',
            'nama_lengkap' => 'Noah Harris',
            'masa_berlaku_ktp' => '2025-12-31',
            'tempat_lahir' => 'Jakarta',
            'tanggal_lahir' => '1990-01-01',
            'jenis_kelamin' => 'Laki-Laki',
            'alamat_ktp' => 'Jl. KTP No. 123',
            'kelurahan_ktp' => 'Kelurahan KTP',
            'kecamatan_ktp' => 'Kecamatan KTP',
            'kota_ktp' => 'Kota KTP',
            'kodepos_ktp' => '12345',
            'alamat' => 'Jl. Alamat No. 456',
            'kelurahan' => 'Kelurahan Alamat',
            'kecamatan' => 'Kecamatan Alamat',
            'kota' => 'Kota Alamat',
            'kodepos' => '54321',
            'no_telepon_rumah' => '021-12345678',
            'no_telepon_hp' => '081234567890',
            'status_tempat_tinggal' => 'Milik Sendiri',
            'menempati_alamat_tsb_sejak' => '2010-01-01',
            'pendidikan_terakhir' => 'SMA',
            'status_perkawinan' => 'Lajang',
            'nama_istri_suami' => 'Jane Doe',
            'jumlah_anak' => '2',
            'nama_ibu_kandung_pemohon' => 'Mother Doe',
            'npwp_pribadi' => '1234567890',
            'nama_ahli_waris' => 'Heir Doe',
            'hubungan_ahli_waris' => 'Anak',
            'no_telp_ext_kantor' => '123',
            'nip' => '123456789',
            'nomor_rekening' => '1234567890',
            'bagian' => 'IT',
            'tgl_masuk_keperusahaan' => '2010-01-01',
            'status_karyawan' => 'Karyawan Tetap',
            'foto' => 'john_doe.jpg',
            'foto_ktp' => 'ktp.jpg',
            'ttd' => 'john_doe_signature.jpg',
            'id_card' => 'id_card.jpg',
            'tanggal_daftar' => '2023-06-11',
            'tanggal_gabung' => '2023-06-11',
            'tanggal_berhenti' => null,
            'tanggal_req_berhenti' => null,
            'sebab_berhenti' => null,
            'password' => bcrypt('123'),
            'email' => 'john@gmail.com',
            'role' => 'kabag',
            'status' => 'Aktif',
        ]);

        DB::table('anggota')->insert([
            'nik' => '726',
            'no_anggota' => '5',
            'nama_lengkap' => 'Ethan Ramirez',
            'masa_berlaku_ktp' => '2025-12-31',
            'tempat_lahir' => 'Jakarta',
            'tanggal_lahir' => '1990-01-01',
            'jenis_kelamin' => 'Laki-Laki',
            'alamat_ktp' => 'Jl. KTP No. 123',
            'kelurahan_ktp' => 'Kelurahan KTP',
            'kecamatan_ktp' => 'Kecamatan KTP',
            'kota_ktp' => 'Kota KTP',
            'kodepos_ktp' => '12345',
            'alamat' => 'Jl. Alamat No. 456',
            'kelurahan' => 'Kelurahan Alamat',
            'kecamatan' => 'Kecamatan Alamat',
            'kota' => 'Kota Alamat',
            'kodepos' => '54321',
            'no_telepon_rumah' => '021-12345678',
            'no_telepon_hp' => '081234567890',
            'status_tempat_tinggal' => 'Milik Sendiri',
            'menempati_alamat_tsb_sejak' => '2010-01-01',
            'pendidikan_terakhir' => 'SMA',
            'status_perkawinan' => 'Lajang',
            'nama_istri_suami' => 'Jane Doe',
            'jumlah_anak' => '2',
            'nama_ibu_kandung_pemohon' => 'Mother Doe',
            'npwp_pribadi' => '1234567890',
            'nama_ahli_waris' => 'Heir Doe',
            'hubungan_ahli_waris' => 'Anak',
            'no_telp_ext_kantor' => '123',
            'nip' => '123456789',
            'nomor_rekening' => '1234567890',
            'bagian' => 'IT',
            'tgl_masuk_keperusahaan' => '2010-01-01',
            'status_karyawan' => 'Karyawan Tetap',
            'foto' => 'john_doe.jpg',
            'foto_ktp' => 'ktp.jpg',
            'ttd' => 'john_doe_signature.jpg',
            'id_card' => 'id_card.jpg',
            'tanggal_daftar' => '2023-06-11',
            'tanggal_gabung' => '2023-06-11',
            'tanggal_berhenti' => null,
            'tanggal_req_berhenti' => null,
            'sebab_berhenti' => null,
            'password' => bcrypt('123'),
            'email' => 'john@gmail.com',
            'role' => 'sdm',
            'status' => 'Aktif',
        ]);

        DB::table('anggota')->insert([
            'nik' => '456',
            'no_anggota' => '2',
            'nama_lengkap' => 'Sophia Anderson',
            'masa_berlaku_ktp' => '2025-12-31',
            'tempat_lahir' => 'Surabaya',
            'tanggal_lahir' => '1995-05-15',
            'jenis_kelamin' => 'Perempuan',
            'alamat_ktp' => 'Jl. KTP No. 456',
            'kelurahan_ktp' => 'Kelurahan KTP',
            'kecamatan_ktp' => 'Kecamatan KTP',
            'kota_ktp' => 'Kota KTP',
            'kodepos_ktp' => '54321',
            'alamat' => 'Jl. Alamat No. 789',
            'kelurahan' => 'Kelurahan Alamat',
            'kecamatan' => 'Kecamatan Alamat',
            'kota' => 'Kota Alamat',
            'kodepos' => '98765',
            'no_telepon_rumah' => '021-98765432',
            'no_telepon_hp' => '081234567890',
            'status_tempat_tinggal' => 'Milik Sendiri',
            'menempati_alamat_tsb_sejak' => '2012-01-01',
            'pendidikan_terakhir' => 'SMA',
            'status_perkawinan' => 'Menikah',
            'nama_istri_suami' => 'John Smith',
            'jumlah_anak' => '1',
            'nama_ibu_kandung_pemohon' => 'Mother Smith',
            'npwp_pribadi' => '0987654321',
            'nama_ahli_waris' => 'Heir Smith',
            'hubungan_ahli_waris' => 'Anak',
            'no_telp_ext_kantor' => '456',
            'nip' => '987654321',
            'nomor_rekening' => '0987654321',
            'bagian' => 'Keuangan',
            'tgl_masuk_keperusahaan' => '2015-01-01',
            'status_karyawan' => 'Karyawan Tetap',
            'foto' => 'jane_smith.jpg',
            'foto_ktp' => 'ktp_jane.jpg',
            'ttd' => 'jane_smith_signature.jpg',
            'id_card' => 'id_card_jane.jpg',
            'tanggal_daftar' => '2023-06-11',
            'tanggal_gabung' => '2023-06-11',
            'tanggal_berhenti' => null,
            'tanggal_req_berhenti' => null,
            'sebab_berhenti' => null,
            'password' => bcrypt('123'),
            'email' => 'jane@gmail.com',
            'role' => 'bendahara',
            'status' => 'Aktif',
        ]);

        DB::table('anggota')->insert([
            'nik' => '789',
            'no_anggota' => '3',
            'nama_lengkap' => 'Olivia Martinez',
            'masa_berlaku_ktp' => '2025-12-31',
            'tempat_lahir' => 'Surabaya',
            'tanggal_lahir' => '1995-05-15',
            'jenis_kelamin' => 'Perempuan',
            'alamat_ktp' => 'Jl. KTP No. 456',
            'kelurahan_ktp' => 'Kelurahan KTP',
            'kecamatan_ktp' => 'Kecamatan KTP',
            'kota_ktp' => 'Kota KTP',
            'kodepos_ktp' => '54321',
            'alamat' => 'Jl. Alamat No. 789',
            'kelurahan' => 'Kelurahan Alamat',
            'kecamatan' => 'Kecamatan Alamat',
            'kota' => 'Kota Alamat',
            'kodepos' => '98765',
            'no_telepon_rumah' => '021-98765432',
            'no_telepon_hp' => '081234567890',
            'status_tempat_tinggal' => 'Milik Sendiri',
            'menempati_alamat_tsb_sejak' => '2012-01-01',
            'pendidikan_terakhir' => 'SMA',
            'status_perkawinan' => 'Menikah',
            'nama_istri_suami' => 'John Smith',
            'jumlah_anak' => '1',
            'nama_ibu_kandung_pemohon' => 'Mother Smith',
            'npwp_pribadi' => '0987654321',
            'nama_ahli_waris' => 'Heir Smith',
            'hubungan_ahli_waris' => 'Anak',
            'no_telp_ext_kantor' => '456',
            'nip' => '987654321',
            'nomor_rekening' => '0987654321',
            'bagian' => 'Keuangan',
            'tgl_masuk_keperusahaan' => '2015-01-01',
            'status_karyawan' => 'Karyawan Tetap',
            'foto' => 'jane_smith.jpg',
            'foto_ktp' => 'ktp_jane.jpg',
            'ttd' => 'jane_smith_signature.jpg',
            'id_card' => 'id_card_jane.jpg',
            'tanggal_daftar' => '2023-06-11',
            'tanggal_gabung' => '2023-06-11',
            'tanggal_berhenti' => null,
            'tanggal_req_berhenti' => null,
            'sebab_berhenti' => null,
            'password' => bcrypt('123'),
            'email' => 'jane@gmail.com',
            'role' => 'sekretaris',
            'status' => 'Aktif',
        ]);

        DB::table('anggota')->insert([
            'nik' => '888',
            'no_anggota' => '7',
            'nama_lengkap' => 'Noah Harris',
            'masa_berlaku_ktp' => '2025-12-31',
            'tempat_lahir' => 'Jakarta',
            'tanggal_lahir' => '1990-01-01',
            'jenis_kelamin' => 'Laki-Laki',
            'alamat_ktp' => 'Jl. KTP No. 123',
            'kelurahan_ktp' => 'Kelurahan KTP',
            'kecamatan_ktp' => 'Kecamatan KTP',
            'kota_ktp' => 'Kota KTP',
            'kodepos_ktp' => '12345',
            'alamat' => 'Jl. Alamat No. 456',
            'kelurahan' => 'Kelurahan Alamat',
            'kecamatan' => 'Kecamatan Alamat',
            'kota' => 'Kota Alamat',
            'kodepos' => '54321',
            'no_telepon_rumah' => '021-12345678',
            'no_telepon_hp' => '081234567890',
            'status_tempat_tinggal' => 'Milik Sendiri',
            'menempati_alamat_tsb_sejak' => '2010-01-01',
            'pendidikan_terakhir' => 'SMA',
            'status_perkawinan' => 'Lajang',
            'nama_istri_suami' => 'Jane Doe',
            'jumlah_anak' => '2',
            'nama_ibu_kandung_pemohon' => 'Mother Doe',
            'npwp_pribadi' => '1234567890',
            'nama_ahli_waris' => 'Heir Doe',
            'hubungan_ahli_waris' => 'Anak',
            'no_telp_ext_kantor' => '123',
            'nip' => '123456789',
            'nomor_rekening' => '1234567890',
            'bagian' => 'IT',
            'tgl_masuk_keperusahaan' => '2010-01-01',
            'status_karyawan' => 'Karyawan Tetap',
            'foto' => 'john_doe.jpg',
            'foto_ktp' => 'ktp.jpg',
            'ttd' => 'john_doe_signature.jpg',
            'id_card' => 'id_card.jpg',
            'tanggal_daftar' => '2023-06-11',
            'tanggal_gabung' => '2023-06-11',
            'tanggal_berhenti' => null,
            'tanggal_req_berhenti' => null,
            'sebab_berhenti' => null,
            'password' => bcrypt('123'),
            'email' => 'john@gmail.com',
            'role' => 'pengawas',
            'status' => 'Aktif',
        ]);
        DB::table('simpanan')->insert([
            'no_anggota' => '7',
            'bulan' => 'Januari',
            'tahun' => '2023',
            'jumlah' => '50000',
        ]);
        DB::table('simpanan')->insert([
            'no_anggota' => '1',
            'bulan' => 'Januari',
            'tahun' => '2022',
            'jumlah' => '50000',
        ]);
        DB::table('simpanan')->insert([
            'no_anggota' => '2',
            'bulan' => 'Januari',
            'tahun' => '2022',
            'jumlah' => '50000',
        ]);
        DB::table('simpanan')->insert([
            'no_anggota' => '3',
            'bulan' => 'Januari',
            'tahun' => '2022',
            'jumlah' => '50000',
        ]);
        DB::table('simpanan')->insert([
            'no_anggota' => '4',
            'bulan' => 'Januari',
            'tahun' => '2022',
            'jumlah' => '50000',
        ]);
        DB::table('simpanan')->insert([
            'no_anggota' => '5',
            'bulan' => 'Januari',
            'tahun' => '2022',
            'jumlah' => '50000',
        ]);


    }
}
